### ISSUE TITLE
Clarity on browser support

### ISSUE THREAD

**Issue by DevSpen** [dopecodez/Wikipedia#37]
The README claims that the package can be used in browsers, but I couldn't find any documentation on it.

Is this actually feasible, how so?

**Comment by DevSpen** [comment]
What about a CDN? For the project I'm working on, I’m not using any frameworks.

**Comment by dopecodez** [comment]
I like the idea of having a cdn that can make life easier to use directly in HTML files or script tags.

Perhaps we could use a framework like https://github.com/cdnjs/cdnjs which will make the process of delivery and updating much easier. 

To answer the question, we don't have a cdn file available now but it is something we should definitely consider doing as it will increase the overall useability of the project.

**Comment by DevSpen** [comment]
> I like the idea of having a cdn that can make life easier to use directly in HTML files or script tags.
> 
> Perhaps we could use a framework like https://github.com/cdnjs/cdnjs which will make the process of delivery and updating much easier.
> 
> To answer the question, we don't have a cdn file available now but it is something we should definitely consider doing as it will increase the overall useability of the project.

Thank you!

**Comment by dopecodez** [comment]
So on taking a look at this `Yarn` already by default provides `unpkg` and `jsDelivr`, both of which are `cdns` available for open source projects. We can use these instead of building a cdn. Take a look at https://yarnpkg.com/package/wikipedia to see the links we get by default. You can see how to use `jsDelivr` by taking a look at this link - https://www.jsdelivr.com/features .

With these features available by default we can use this and not spend time on creating another cdn.
